"use client";

import React from "react";
import { DollarSign, Zap, Award, Users, TrendingUp } from "lucide-react";
import { SubscriptionStats } from "@/lib/data/subscriptions";

interface SubscriptionCardsProps {
  stats: SubscriptionStats;
  className?: string;
}

export function SubscriptionCards({ stats, className = "" }: SubscriptionCardsProps) {
  return (
    <div className={`space-y-3 ${className}`}>
      {/* Section Sub-heading */}
      <div className="flex items-center justify-between">
        <h2 className="text-xs font-semibold uppercase tracking-wider text-[#8A8A85]">
          Subscriptions Overview
        </h2>
        <span className="text-[11px] font-medium text-[#71716D] bg-[#F5F5F3] px-2.5 py-0.5 rounded-full border border-[#E8E8E3]">
          Live Billing Sync
        </span>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-3.5">
        {/* 1. Highlight Card: Amount Generated / Earnings by Subscriptions */}
        <div className="bg-[#141413] text-white rounded-xl p-4.5 flex flex-col justify-between shadow-xs border border-[#262624] relative overflow-hidden group hover:border-[#3A3A36] transition-all">
          <div className="absolute top-0 right-0 w-32 h-32 bg-white/[0.03] rounded-full blur-2xl pointer-events-none -mr-8 -mt-8" />
          
          <div className="flex items-center justify-between gap-2">
            <span className="text-xs font-medium text-[#A3A39E] tracking-tight">
              Amount generated by subscriptions
            </span>
            <div className="w-7 h-7 rounded-lg bg-white/10 flex items-center justify-center shrink-0">
              <DollarSign className="w-4 h-4 text-[#E6E6E1]" />
            </div>
          </div>

          <div className="mt-3">
            <div className="flex items-baseline gap-2">
              <span className="text-2xl sm:text-3xl font-serif font-semibold tracking-tight text-white">
                ${stats.totalAmountGenerated.toLocaleString()}
              </span>
              <span className="text-[10px] font-medium text-[#34D399] bg-[#34D399]/10 px-1.5 py-0.5 rounded border border-[#34D399]/20">
                +18.4%
              </span>
            </div>
            <p className="mt-1 text-[11px] text-[#A3A39E] leading-relaxed">
              ${stats.monthlyRecurringRevenue.toLocaleString()}/mo MRR · Total earnings generated
            </p>
          </div>
        </div>

        {/* 2. Pro Subscribers */}
        <div className="bg-white border border-[#E8E8E3] rounded-xl p-4.5 flex flex-col justify-between shadow-2xs hover:border-[#CFCFC9] transition-all">
          <div className="flex items-center justify-between gap-2">
            <span className="text-xs font-medium text-[#6E6E69] tracking-tight">
              Pro Subscribers
            </span>
            <div className="w-7 h-7 rounded-lg bg-[#FAF9F5] border border-[#E8E8E3] flex items-center justify-center shrink-0">
              <Zap className="w-3.5 h-3.5 text-[#B8532F]" />
            </div>
          </div>

          <div className="mt-3">
            <div className="flex items-baseline gap-2">
              <span className="text-2xl font-serif font-semibold tracking-tight text-[#141413]">
                {stats.proCount}
              </span>
              <span className="text-[10px] font-medium text-[#B8532F] bg-[#B8532F]/10 px-1.5 py-0.5 rounded border border-[#B8532F]/20">
                {stats.proPercentage}% share
              </span>
            </div>
            <p className="mt-1 text-[11px] text-[#8A8A85] leading-relaxed">
              $29 / month · Standard Pro tier
            </p>
          </div>
        </div>

        {/* 3. Elite Subscribers */}
        <div className="bg-white border border-[#E8E8E3] rounded-xl p-4.5 flex flex-col justify-between shadow-2xs hover:border-[#CFCFC9] transition-all">
          <div className="flex items-center justify-between gap-2">
            <span className="text-xs font-medium text-[#6E6E69] tracking-tight">
              Elite Subscribers
            </span>
            <div className="w-7 h-7 rounded-lg bg-[#FAF9F5] border border-[#E8E8E3] flex items-center justify-center shrink-0">
              <Award className="w-3.5 h-3.5 text-[#141413]" />
            </div>
          </div>

          <div className="mt-3">
            <div className="flex items-baseline gap-2">
              <span className="text-2xl font-serif font-semibold tracking-tight text-[#141413]">
                {stats.eliteCount}
              </span>
              <span className="text-[10px] font-medium text-[#28633B] bg-[#28633B]/10 px-1.5 py-0.5 rounded border border-[#28633B]/20">
                {stats.elitePercentage}% share
              </span>
            </div>
            <p className="mt-1 text-[11px] text-[#8A8A85] leading-relaxed">
              $99 / month · VIP Studio tier
            </p>
          </div>
        </div>

        {/* 4. Free Members */}
        <div className="bg-white border border-[#E8E8E3] rounded-xl p-4.5 flex flex-col justify-between shadow-2xs hover:border-[#CFCFC9] transition-all">
          <div className="flex items-center justify-between gap-2">
            <span className="text-xs font-medium text-[#6E6E69] tracking-tight">
              Free Members
            </span>
            <div className="w-7 h-7 rounded-lg bg-[#FAF9F5] border border-[#E8E8E3] flex items-center justify-center shrink-0">
              <Users className="w-3.5 h-3.5 text-[#6E6E69]" />
            </div>
          </div>

          <div className="mt-3">
            <div className="flex items-baseline gap-2">
              <span className="text-2xl font-serif font-semibold tracking-tight text-[#141413]">
                {stats.freeCount}
              </span>
              <span className="text-[10px] font-medium text-[#71716D] bg-[#F5F5F3] px-1.5 py-0.5 rounded border border-[#E8E8E3]">
                Base tier
              </span>
            </div>
            <p className="mt-1 text-[11px] text-[#8A8A85] leading-relaxed">
              Community explorer members
            </p>
          </div>
        </div>

        {/* 5. Paid Conversion Rate */}
        <div className="bg-white border border-[#E8E8E3] rounded-xl p-4.5 flex flex-col justify-between shadow-2xs hover:border-[#CFCFC9] transition-all">
          <div className="flex items-center justify-between gap-2">
            <span className="text-xs font-medium text-[#6E6E69] tracking-tight">
              Paid Conversion
            </span>
            <div className="w-7 h-7 rounded-lg bg-[#FAF9F5] border border-[#E8E8E3] flex items-center justify-center shrink-0">
              <TrendingUp className="w-3.5 h-3.5 text-[#28633B]" />
            </div>
          </div>

          <div className="mt-3">
            <div className="flex items-baseline gap-2">
              <span className="text-2xl font-serif font-semibold tracking-tight text-[#141413]">
                {stats.conversionRate}%
              </span>
              <span className="text-[10px] font-medium text-[#28633B] bg-[#EAF2EC] px-1.5 py-0.5 rounded border border-[#CDE3D3]">
                {stats.totalPaidSubscribers} paid
              </span>
            </div>
            <p className="mt-1 text-[11px] text-[#8A8A85] leading-relaxed">
              Platform membership adoption
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
